nikolausers/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^', include('sites.urls')),
    re_path(r'^admin/', admin.site.urls),
]

admin.site.site_title = admin.site.site_header = admin.site.index_title = 'Nikola Users — Administration'

sites/urls.py
from django.urls import re_path as url
from . import views

app_name = 'sites'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/?$', views.add, name='add'),
    url(r'^edit/?$', views.edit, name='edit'),
    url(r'^remove/?$', views.remove, name='remove'),
    url(r'^check/?$', views.check, name='check'),
    url(r'^api/check$', views.api_check, name='api_check'),
    url(r'^tos/?$', views.tos, name='tos'),
    url(r'^lang/?$', views.langlist, name='langlist'),
    url(r'^lang/(?P<language_code>[a-z]{2,5})/?$', views.lang, name='lang'),
    url(r'^lang/(?P<language_code>[a-z]{2,5})_(?P<country_code>[A-Z]{2,5})/?$', views.lang, name='lang'),
    url(r'^downloads/?$', views.downloads, name='downloads'),
    url(r'^downloads/urls.txt$', views.download_urls_txt, name='download_urls_txt'),
    url(r'^downloads/urls.json$', views.download_urls_json, name='download_urls_json'),
    url(r'^downloads/featured.json$', views.download_featured_json, name='download_featured_json'),
    url(r'^downloads/sites.json$', views.download_sites_json, name='download_sites_json'),
]

templates/add-ack.html
{% extends "base.html" %}
{% block content %}
<p class="text-success lead">Request sent!</p>
{% if email_succeeded %}
<p>Administrators were informed of your request.  Your site will be added within 48 hours.</p>
{% else %}
<p class="text-warning">WARNING: Administrators were not informed of your request because sending e-mail failed. Please report this to <a href="https://getnikola.com/contact.html">the Nikola team</a> (preferably on Twitter, or personally to Chris Warrick through e-mail)</p>
{% endif %}

<p>The administrators reserve the right to alter the information, or reject your site altogether.</p>

<p>Here is the information you provided:</p>
<dl class="dl-horizontal">
    <dt>Title</dt>
    <dd>{{ site.title }}</dd>
    <dt>Author</dt>
    <dd>{{ site.author }}</dd>
    <dt>URL</dt>
    <dd>{{ site.clickable_url }}</dd>
    <dt>Description</dt>
    <dd>{{ site.description_formatted }}</dd>
    <dt>Source</dt>
    <dd>{% if site.sourcelink %}{{ site.clickable_sourcelink }}{% else %}none{% endif %}</dd>
    <dt>Languages</dt>
    {% if blacklisted %}
    <dd>{{ fake_languages|join:", " }}</dd>
    {% else %}
    <dd>{{ site.languages.all|join:", " }}</dd>
    {% endif %}
    <dt>Date</dt>
    {% if blacklisted %}
    <dd>{% now "Y-m-d H:i:s" %}</dd>
    {% else %}
    <dd>{{ site.date|date:"Y-m-d H:i:s" }}</dd>
    {% endif %}
</dl>
{% endblock %}

templates/add-error.html
{% extends "base.html" %}
{% block content %}
<p class="text-danger lead">Something went wrong.</p>
{% if reason == 'tos_pub' %}
<p class="text-danger">You need to accept the Terms of Service and acknowledge data publication.</p>
{% elif reason == 'duplicate' %}
<p class="text-danger">There is an entry for this page already — you should <a href="/edit/">request an edit</a>.</p>
{% else %}
<p class="text-danger">The following errors occurred:</p>
<div class="text-danger">
{{ reason }}
</div>

{% endif %}

<p>Please press the Back button and fix those problems.</p>
{% endblock %}

templates/add.html
{% extends "base.html" %}
{% block content %}

<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="inputTitle">Title</label>
        <div class="col-lg-10">
            <input type="text" class="form-control" name="title" id="inputTitle" placeholder="Title"
            required maxlength="100">
            <span class="help-block">Should be the same as <tt>BLOG_TITLE</tt>.</span>
        </div>
    </div>
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="inputAuthor">Author</label>
        <div class="col-lg-10">
            <input type="text" class="form-control" name="author" id="inputAuthor" placeholder="Author"
            required maxlength="100">
            <span class="help-block">Don’t use an e-mail; feel free to use a pseudonym.</span>
        </div>
    </div>
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="inputURL">URL</label>
        <div class="col-lg-10">
            <input type="url" class="form-control" name="url" id="inputURL" placeholder="URL" required maxlength="512">
            <span class="help-block">Should be the same as <tt>SITE_URL</tt>.</span>
        </div>
    </div>
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="inputDescription">Description</label>
        <div class="col-lg-10">
            <textarea name="description" class="form-control" id="inputDescription" placeholder="Description"
                maxlength="250" required rows="5"></textarea>
            <span class="help-block">Up to 250 characters.  (we’re quite
                generous!)</span>
        </div>
    </div>
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="inputSource">Site source</label>
        <div class="col-lg-10">
            <input type="url" class="form-control" name="sourcelink" id="inputSource"
            placeholder="Site source" maxlength="512">
            <span class="help-block">Link to your site source on GitHub (if any)</span>
        </div>
    </div>
    <div class="form-group form-row">
        <label class="control-label col-lg-2" for="selectLanguages">Languages</label>
        <div class="col-lg-10">
            <select multiple required name="languages" id="selectLanguages" class="form-control">
                {% for l in langs %}
                <option value="{{ l.code }}">{{ l }}</option>
                {% endfor %}
            </select>
            <span class="help-block">Languages your site is in.  (choose at
                least one — use <strong>Ctrl</strong>/<strong>Cmd</strong> to choose multiple)</span>
            <p class="text-warning mb-0">If your language is not on the list,
            please <a
                href="https://github.com/getnikola/nikola-users/issues">report
                an Issue on GitHub</a>.</p>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="offset-lg-2 col-lg-10">
            <label class="checkbox mb-3">
                <input name="tos" type="checkbox" required> I agree to the <a href="/tos/">Terms of Service and Privacy Policy</a>.</label>
            <label class="checkbox mb-3">
                <input name="ack_publishing" type="checkbox" required> I acknowledge that all the information I submit will be displayed publicly. You may revise or remove all information at any time by e-mailing the site administrators.
            </label>
            <button type="submit" class="btn btn-primary">Request addition</button>
        </div>
    </div>
</form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# " lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title1 %}{{ title }}{% endblock %} | Some Sites Using Nikola</title>
<link href="https://getnikola.com/assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#f5ab14">
<!--[if lt IE 9]><script src="https://getnikola.com/assets/js/html5.js"></script><![endif]-->
</head>
<link href="{% static "users.min.css" %}" rel="stylesheet" type="text/css">
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top mb-4"><div class="container">
<!-- This keeps the margins nice -->
        <a class="navbar-brand" href="https://getnikola.com/">
            <img src="https://getnikola.com/assets/img/logo.svg" alt="Nikola" id="logo" class="d-inline-block align-top"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="bs-navbar">
            <ul class="navbar-nav mr-auto">
<li class="nav-item dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Documentation</a>
            <div class="dropdown-menu">
                    <a href="https://getnikola.com/documentation.html" class="dropdown-item"><strong>Documentation Index</strong></a>
                    <a href="https://getnikola.com/getting-started.html" class="dropdown-item"><strong>Getting Started</strong></a>
                    <a href="https://getnikola.com/handbook.html" class="dropdown-item"><strong>Handbook</strong></a>
                    <a href="https://getnikola.com/features/index.html" class="dropdown-item"><strong>Features</strong></a>
                    <a href="https://getnikola.com/conf.html" class="dropdown-item">conf.py</a>
                    <a href="https://getnikola.com/changes.html" class="dropdown-item">Changelog</a>
                    <a href="https://getnikola.com/creating-a-theme.html" class="dropdown-item">Theming Tutorial</a>
                    <a href="https://getnikola.com/theming.html" class="dropdown-item">Theming Reference</a>
                    <a href="https://getnikola.com/extending.html" class="dropdown-item">Extending</a>
                    <a href="https://getnikola.com/internals.html" class="dropdown-item">Internals</a>
                    <a href="https://getnikola.com/creating-a-site-not-a-blog-with-nikola.html" class="dropdown-item">Creating a Site (Not a Blog)</a>
                    <a href="https://getnikola.com/license.html" class="dropdown-item">License</a>
            </div>
            </li>
<li class="nav-item dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Support &amp; Contact</a>
            <div class="dropdown-menu">
                    <a href="https://github.com/getnikola/nikola/issues" class="dropdown-item">Issue Tracker</a>
                    <a href="https://groups.google.com/group/nikola-discuss" class="dropdown-item">Mailing List</a>
                    <a href="https://twitter.com/GetNikola" class="dropdown-item">Twitter</a>
                    <a href="https://irclogs.getnikola.com/" class="dropdown-item">IRC logs (#nikola@freenode)</a>
                    <a href="https://getnikola.com/contact.html" class="dropdown-item"><strong>All support options</strong></a>
            </div>
            </li>
<li class="nav-item dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add-ons</a>
            <div class="dropdown-menu">
                    <a href="https://themes.getnikola.com" class="dropdown-item">Themes</a>
                    <a href="https://plugins.getnikola.com" class="dropdown-item">Plugins</a>
                    <a href="https://github.com/getnikola/shortcodes" class="dropdown-item">Shortcodes</a>
            </div>
            </li>
<li class="nav-item dropdown">
<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Development</a>
            <div class="dropdown-menu">
                    <a href="https://github.com/getnikola/nikola" class="dropdown-item"><strong>Source code (GitHub)</strong></a>
                    <a href="https://github.com/getnikola/nikola/issues" class="dropdown-item">Issue Tracker</a>
                    <a href="https://getnikola.com/changes.html" class="dropdown-item">Changelog</a>
                    <a href="https://getnikola.com/license.html" class="dropdown-item">License</a>
                    <a href="https://getnikola.com/authors.html" class="dropdown-item">Contributors</a>
            </div>
                </li>
<li class="nav-item">
<a href="https://getnikola.com/blog/" class="nav-link">Blog</a>
                </li>
<li class="nav-item">
    <a href="/" class="nav-link active">Users<span class="sr-only"> (active)</span></a>

                
            </li>
</ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
<ul class="nav nav-pills">
    {% for mlink, mtitle, mpage in menu %}
    <li class="nav-item"><a class="nav-link{% if mpage == page %} active{% endif %}" href="{{ mlink }}">{{ mtitle }}</a></li>
    {% endfor %}
</ul>

<h1 class="entry-title">{% block title2 %}{{ title }}{% endblock title2 %}</h1>
{% block subtitle %}{% endblock %}

{% block content %}
{% endblock %}
<footer id="footer">
    Contents © 2012–2026 <a href="mailto:users@getnikola.com">Roberto Alsina
        and Chris Warrick</a>  |  Powered by Django  |  <a
        href="https://twitter.com/intent/user?screen_name=GetNikola">Follow Nikola on Twitter</a>  |  Theme is <a href="https://bootswatch.com/cerulean/">Cerulean</a>
    <p>This site is using cookies for authentication and security purposes.</p>
</footer>
</div>
</div>
<script src="https://getnikola.com/assets/js/all-nocdn.js" type="text/javascript"></script>
{% block extra_js %}{% endblock %}
<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
</body>
</html>

templates/check.html
{% extends "base.html" %}
{% block content %}
<div>
<p>This feature has been disabled. If you want to test a site, use the following Python script:</p>
<table class="codetable"><tr>
<td class="linenos"><div class="linenodiv"><pre><a href="#listingscheckerpy-1"> 1</a>
<a href="#listingscheckerpy-2"> 2</a>
<a href="#listingscheckerpy-3"> 3</a>
<a href="#listingscheckerpy-4"> 4</a>
<a href="#listingscheckerpy-5"> 5</a>
<a href="#listingscheckerpy-6"> 6</a>
<a href="#listingscheckerpy-7"> 7</a>
<a href="#listingscheckerpy-8"> 8</a>
<a href="#listingscheckerpy-9"> 9</a>
<a href="#listingscheckerpy-10">10</a>
<a href="#listingscheckerpy-11">11</a>
<a href="#listingscheckerpy-12">12</a>
<a href="#listingscheckerpy-13">13</a>
<a href="#listingscheckerpy-14">14</a>
<a href="#listingscheckerpy-15">15</a>
<a href="#listingscheckerpy-16">16</a>
<a href="#listingscheckerpy-17">17</a>
<a href="#listingscheckerpy-18">18</a></pre></div></td>
<td class="code"><pre class="code literal-block"><a name="listingscheckerpy-1"></a><span class="kn">import</span> <span class="nn">requests</span>
<a name="listingscheckerpy-2"></a>
<a name="listingscheckerpy-3"></a><span class="n">url</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">"URL to check: "</span><span class="p">)</span>
<a name="listingscheckerpy-4"></a><span class="k">if</span> <span class="ow">not</span> <span class="n">url</span><span class="o">.</span><span class="n">endswith</span><span class="p">(</span><span class="s1">'/rss.xml'</span><span class="p">):</span>
<a name="listingscheckerpy-5"></a>    <span class="n">url</span> <span class="o">+=</span> <span class="s2">"/rss.xml"</span>
<a name="listingscheckerpy-6"></a><span class="n">r</span> <span class="o">=</span> <span class="n">requests</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">url</span><span class="p">)</span>
<a name="listingscheckerpy-7"></a><span class="n">patterns</span> <span class="o">=</span> <span class="p">[(</span><span class="sa">b</span><span class="s1">'&lt;generator&gt;https://getnikola.com/&lt;/generator&gt;'</span><span class="p">,</span> <span class="s1">'Nikola v7.8.2+'</span><span class="p">),</span>
<a name="listingscheckerpy-8"></a>            <span class="p">(</span><span class="sa">b</span><span class="s1">'&lt;generator&gt;https://getnikola.com/&lt;/generator&gt;'</span><span class="p">,</span> <span class="s1">'Nikola v7.6.1-v7.8.1'</span><span class="p">),</span>
<a name="listingscheckerpy-9"></a>            <span class="p">(</span><span class="sa">b</span><span class="s1">'&lt;generator&gt;http://getnikola.com/&lt;/generator&gt;'</span><span class="p">,</span> <span class="s1">'Nikola v7.0.0-v7.6.0'</span><span class="p">),</span>
<a name="listingscheckerpy-10"></a>            <span class="p">(</span><span class="sa">b</span><span class="s1">'&lt;generator&gt;Nikola &lt;http://getnikola.com/&gt;&lt;/generator&gt;'</span><span class="p">,</span> <span class="s1">'Nikola v6.3.0-v6.4.0'</span><span class="p">),</span>
<a name="listingscheckerpy-11"></a>            <span class="p">(</span><span class="sa">b</span><span class="s1">'&lt;generator&gt;nikola&lt;/generator&gt;'</span><span class="p">,</span> <span class="s1">'Nikola v6.2.1 or older'</span><span class="p">)]</span>
<a name="listingscheckerpy-12"></a><span class="n">result</span> <span class="o">=</span> <span class="o">-</span><span class="mi">1</span>
<a name="listingscheckerpy-13"></a><span class="k">for</span> <span class="n">pattern</span><span class="p">,</span> <span class="n">description</span> <span class="ow">in</span> <span class="n">patterns</span><span class="p">:</span>
<a name="listingscheckerpy-14"></a>    <span class="k">if</span> <span class="n">pattern</span> <span class="ow">in</span> <span class="n">r</span><span class="o">.</span><span class="n">content</span><span class="p">:</span>
<a name="listingscheckerpy-15"></a>        <span class="k">print</span><span class="p">(</span><span class="n">description</span><span class="p">)</span>
<a name="listingscheckerpy-16"></a>        <span class="nb">exit</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
<a name="listingscheckerpy-17"></a><span class="k">print</span><span class="p">(</span><span class="s2">"Not a Nikola site"</span><span class="p">)</span>
<a name="listingscheckerpy-18"></a><span class="nb">exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
</pre></td>
</tr></table>
</div>
{% endblock %}

templates/downloads.html
{% extends "base.html" %}
{% block content %}
<p>We offer the ability to download the sites list in multiple formats. The information may only be used for non-commercial purposes.</p>
<ul>
    <li><a href="{% url "sites:download_urls_txt" %}">Only URLs, .txt format</a></li>
    <li><a href="{% url "sites:download_urls_json" %}">URLs and titles, .json format</a></li>
    <li><a href="{% url "sites:download_featured_json" %}">Full data on {{ featured_count }} featured sites, .json format</a></li>
</ul>
<p>If you want information on all {{ all_count }} sites, please contact us (state the reason): <a href="mailto:users@getnikola.com">users@getnikola.com</a>.</p>
{% if user.is_authenticated %}
<a href="{% url "sites:download_sites_json" %}">Download full site data</a> (logged-in users only)
{% endif %}

{% endblock %}

templates/edit-remove.html
{% extends "base.html" %}
{% block content %}
<p>
In order to {{ page }} your site’s entry, simply send an e-mail to <a
    href="mailto:users@getnikola.com">users@getnikola.com</a>
— make sure to prove you own the site. {% if page == "remove" %}Including a reason is recommended.{% endif %}
</p>

<p>We require using e-mail, because someone might make a fraudulent request.
    Sorry for the inconvenience.</p>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
{% if page == 'home' %}
<p>
Below is a selection of the many websites made by users of Nikola. Visit a
few sites and see some of what is possible to achieve with Nikola.
</p>
<p>
If you have made your own Nikola site, you can <a href="/add/">add it to the index</a>.
</p>
{% endif %}

{% if count == 0 %}
<p class="text-error">No pages found…</p>
{% else %}
<div class="row pages-line">
    {% for site in sites %}
    <div class="col-md-3"><div class="card {% if site.featured %} featured bg-light{% endif %}">
            <div class="card-body">
                <header style="margin: 0; clear: both;">
                    <h4 class="pagelink">{{ site.link }}<br>
                        <small class="metadata">
                            <p class="byline author vcard">by {{ site.author }}</p>
                            {% if site.sourcelink %}
                            <p class="sourceline">{{ site.clickable_sourcelink }}</p>
                            {% endif %}
                            <p class="langline">
                            {% for lang in site.languages.all %}
                            <a href="/lang/{{ lang.code }}/" class="pagelang" title="{{ lang.name }}">{{ lang.code }}</a>
                            {% empty %}
                            <span class="pagelang pagelang-unknown" title="Unknown">??</span>
                            {% endfor %}
                            </p>
                        </small>
                    </h4>
                </header>
                {{ site.description_formatted }}
                {% if site.featured_reason %}
                <footer class="text-muted featured-reason">
                    {{ site.featured_reason }}
                </footer>
                {% endif %}
            </div></div></div>
            {% if forloop.counter|divisibleby:"4" %}
</div><div class="row pages-line">
    {% endif %}
    {% endfor %}
</div>

<!-- Other Sites -->
<div class="row pages-line">
    {% for site in other_sites %}
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <header style="margin: 0; clear: both;">
                    <h4 class="pagelink">{{ site.link }}<br>
                        <small class="metadata">
                            <p class="byline author vcard">by {{ site.author }}</p>
                            {% if site.sourcelink %}
                            <p class="sourceline">{{ site.clickable_sourcelink }}</p>
                            {% endif %}
                            <p class="langline">
                            {% for lang in site.languages.all %}
                            <span class="pagelang" title="{{ lang.name }}">{{ lang.code }}</span>
                            {% empty %}
                            <span class="pagelang pagelang-unknown" title="Unknown">??</span>
                            {% endfor %}
                            </p>
                        </small>
                    </h4>
                </header>
                {{ site.description }}
            </div></div></div>
            {% if forloop.counter|divisibleby:"4" %}
</div><div class="row pages-line unstyled">
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endblock content %}
{% block js %}
<script>
    $('#edit-btn').click(function() {
        $('#edit-alert').slideToggle();
        return false;
    });
$('#remove-btn').click(function() {
    $('#remove-alert').slideToggle();
    return false;
});
</script>
{% endblock js %}

templates/languages.html
{% extends "base.html" %}
{% block content %}
<ul>
{% for l in languages %}
    <li><a href="/lang/{{ l.code }}/">{{ l }}</a></li>
{% endfor %}
</ul>
<h2>Language groups</h2>
<ul>
{% for lc, lg in language_groups.items %}
    <li><a href="/lang/{{ lc }}/">{{ lg }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/tos.html
{% extends "base.html" %}
{% block content %}
<h2>General service terms</h2>
<ol>
    <li>The Service is provided <strong>as-is</strong>.  Any express or implied
    warranties, including, but not limited to, the implied warranties of
    merchantability and fitness for a particular purpose are disclaimed.</li>
    <li>Roberto Alsina and Chris Warrick do not guarantee error-free
    operation of the Service.</li>
    <li>In no event shall Roberto Alsina and Chris Warrick be liable for any
    damages caused by the use of the Service.</li>
    <li>You must be at least 13 years old to use the Service, as per the COPPA
    (US law).  You must also be a human being, robots and automated
    scripts are not allowed to use the Service.</li>
    <li>Roberto Alsina and Chris Warrick promise not to sell or abuse any of
    the details you entered while registering with the Service.</li>
</ol>

<h2>Content</h2>
<ol>
    <li>You are responsible for all the content you post.</li>
    <li>Content is pre-screened before publication; any abusive materials will
    be removed.</li>
    <li>Roberto Alsina and Chris Warrick have every right to remove any
    content that may have unlawful, offensive, or otherwise abusive content.</li>
    <li>Roberto Alsina and Chris Warrick claim no copyright or IP over your
    content.</li>
    <li>You must not post spam.</li>
    <li>Content posted by you must not harm the Service in any way.</li>
    <li>By submitting any information, you acknowldge that all information will be displayed publicly. You may revise or remove all information at any time by e-mailing the site administrators.</li>
</ol>
{% endblock %}